// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using w0448225CourseMap.Data;

#nullable disable

namespace w0448225CourseMap.Migrations
{
    [DbContext(typeof(w0448225CourseMapContext))]
    [Migration("20230125220132_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicYearSemester", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicYearId1")
                        .HasColumnType("int");

                    b.HasKey("AcademicYearId", "AcademicYearId1");

                    b.HasIndex("AcademicYearId1");

                    b.ToTable("AcademicYearSemester");
                });

            modelBuilder.Entity("CourseCourseOffering", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId1")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "CourseId1");

                    b.HasIndex("CourseId1");

                    b.ToTable("CourseCourseOffering");
                });

            modelBuilder.Entity("CourseOfferingDiplomaYearSection", b =>
                {
                    b.Property<int>("DiplomaYearSectionId")
                        .HasColumnType("int");

                    b.Property<int>("DiplomaYearSectionId1")
                        .HasColumnType("int");

                    b.HasKey("DiplomaYearSectionId", "DiplomaYearSectionId1");

                    b.HasIndex("DiplomaYearSectionId1");

                    b.ToTable("CourseOfferingDiplomaYearSection");
                });

            modelBuilder.Entity("CourseOfferingInstructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId1")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "InstructorId1");

                    b.HasIndex("InstructorId1");

                    b.ToTable("CourseOfferingInstructor");
                });

            modelBuilder.Entity("CourseOfferingSemester", b =>
                {
                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId1")
                        .HasColumnType("int");

                    b.HasKey("SemesterId", "SemesterId1");

                    b.HasIndex("SemesterId1");

                    b.ToTable("CourseOfferingSemester");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.AdvisingAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiplomaYearSectionId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaYearSectionId")
                        .IsUnique();

                    b.HasIndex("InstructorId");

                    b.ToTable("AdvisingAssignments");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.CourseOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("DiplomaYearSectionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDirectedElective")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<int?>("SemesterId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CourseOfferings");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("CoursePrerequisites");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Diploma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Diplomas");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.DiplomaYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiplomaId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaId");

                    b.ToTable("DiplomaYears");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.DiplomaYearSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("DiplomaYearId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("DiplomaYearId");

                    b.ToTable("DiplomaYearSections");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicYearId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("AcademicYearSemester", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.Semester", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseCourseOffering", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.CourseOffering", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseOfferingDiplomaYearSection", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.CourseOffering", null)
                        .WithMany()
                        .HasForeignKey("DiplomaYearSectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.DiplomaYearSection", null)
                        .WithMany()
                        .HasForeignKey("DiplomaYearSectionId1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseOfferingInstructor", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.CourseOffering", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseOfferingSemester", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.CourseOffering", null)
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.Semester", null)
                        .WithMany()
                        .HasForeignKey("SemesterId1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("w0448225CourseMap.Models.AdvisingAssignment", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.DiplomaYearSection", "DiplomaYearSection")
                        .WithOne("AdvisingAssignment")
                        .HasForeignKey("w0448225CourseMap.Models.AdvisingAssignment", "DiplomaYearSectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.Instructor", "Instructor")
                        .WithMany("AdvisingAssignments")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiplomaYearSection");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.Course", "Prerequisite")
                        .WithMany("IsPrerequisiteFor")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.DiplomaYear", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.Diploma", "Diploma")
                        .WithMany("DiplomaYears")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.DiplomaYearSection", b =>
                {
                    b.HasOne("w0448225CourseMap.Models.AcademicYear", "AcademicYear")
                        .WithMany("DiplomaYearSection")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("w0448225CourseMap.Models.DiplomaYear", "DiplomaYear")
                        .WithMany("DiplomaYearSections")
                        .HasForeignKey("DiplomaYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("DiplomaYear");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.AcademicYear", b =>
                {
                    b.Navigation("DiplomaYearSection");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Course", b =>
                {
                    b.Navigation("IsPrerequisiteFor");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Diploma", b =>
                {
                    b.Navigation("DiplomaYears");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.DiplomaYear", b =>
                {
                    b.Navigation("DiplomaYearSections");
                });

            modelBuilder.Entity("w0448225CourseMap.Models.DiplomaYearSection", b =>
                {
                    b.Navigation("AdvisingAssignment")
                        .IsRequired();
                });

            modelBuilder.Entity("w0448225CourseMap.Models.Instructor", b =>
                {
                    b.Navigation("AdvisingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
